---
title: "Wine_screencast"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(broom)
theme_set(theme_light())
wine_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% 
  select(-X1) %>% # clean a bit
  extract(title, "year", "(20\\d\\d)", convert = T, remove = F) %>% 
  mutate(year = ifelse(year>=1900, year, NA))
```

```{r}
# library(RVerbalExpressions) 
# pattern <- rx_begin_capture() %>%  rx_digit() %>% rx_multiple(4) %>% rx_end_capture()
```


```{r}
wine_ratings %>% glimpse() # could predict the pionts 80-100 from other information
```

```{r}
wine_ratings %>% 
  count(country, sort = T) # typical wine countries
wine_ratings %>% 
  count(designation, sort = T) # anytime a categorical data, count it!
  
wine_ratings %>% 
  count(country, region_1, sort = T) # not meaningful to count region without country

wine_ratings %>% 
  count(taster_name,  sort = T) 

wine_ratings %>% 
  count(variety,  sort = T) 

wine_ratings %>% 
  filter(!is.na(designation)) %>% 
  count(variety,  designation, sort = T) 

wine_ratings %>% 
  count(winery,  sort = T) 

wine_ratings %>%
  ggplot(aes(year))+
  geom_histogram()

wine_ratings %>%
  ggplot(aes(points))+
  geom_histogram(binwidth = 1)

wine_ratings %>% 
  ggplot(aes(price))+
  geom_histogram()+
  scale_x_log10()
 
```
```{r}
ggplot(wine_ratings, aes(price, points))+
  geom_point(alpha=.1)+
  scale_x_log10()+
  geom_smooth(method = "lm") # this chart confirms relationship and price should be a predictor

lm(points~log2(price), wine_ratings) %>% summary()
```
Every time the price doubles, points expected to increase by 2
```{r}

model <- wine_ratings %>% 
  replace_na(list(taster_name = "Missing",
                  country = "Missing"
                  )) %>% 
  mutate(taster_name = fct_lump(taster_name, 6) %>% fct_relevel("Missing")) %>%   
  mutate(country = fct_lump(country, 7) %>% fct_relevel("US")) %>% 
  lm(points~log2(price) + country + year + taster_name, data =.) 

model %>% 
  tidy(conf.int = T) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = term %>%
           str_replace("country", "Country: ") %>%
           str_replace("taster_name", "Taster: ") %>% 
           fct_reorder(estimate)
         ) %>%
  ggplot(aes(estimate, term)) +
  geom_point()+
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high))

```

all coefs have significance, not to worry

However, the model only explained 0.4 of the variance in points. 

```{r}
model %>% 
  augment(data = wine_ratings) %>% 
  ggplot(aes(.fitted, points))+
  geom_point(alpha = .1)

anova(model) %>% 
  tidy() %>% 
  mutate(portion = sumsq / sum(sumsq))
```
### Lasso regression on words in description
```{r}
library(tidytext)
```
```{r}
wine_rating_words <- wine_ratings %>% 
  mutate(wine_id = row_number()) %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words, by = "word") 

wine_rating_words <- wine_rating_words %>% 
  filter(!word %in% c("wine", "drink"))
```

```{r}
wine_rating_words %>% 
  count(word, sort = T)
```


```{r, include =F, eval=F}
wine_ratings %>%
  mutate(country = fct_lump(country, 7),
         country = fct_relevel(country, "US"),
         country = fct_reorder(country,points)
         ) %>%
  ggplot(aes(country, points))+
  geom_boxplot()+
  coord_flip()

wine_ratings %>% 
  ggplot(aes(year, points, group = year))+
  geom_boxplot()

wine_ratings %>% 
  group_by(year) %>% 
  summarise(avg_points = mean(points), n = n())  
  ggplot(aes(year, avg_points))+
  geom_line() # 2017 have few data points, still may try to use year as predictor

wine_ratings %>% 
  mutate(reviewer = fct_lump(taster_name, 10) %>% fct_reorder(points)) %>% 
  ggplot(aes(reviewer, points))+
  geom_boxplot()+
  coord_flip()
```

